### ISSUE TITLE
Compatibility PHP 5.5v

### ISSUE THREAD

**Issue by milorojas** [marsoltys/yii2user#4]
Hey its me again sorry if i am very annoying but can we do something about a compatibility for PHP 5.5 versions because on `components/User.php` the `getFlashes()` method has a flag `ARRAY_FILTER_USE_KEY` (line 128) that filter flag was added in PHP 5.6.0, and a lot of people works on PHP 5.5 can you change that  filter or just delete it.

i just deleted the `, ARRAY_FILTER_USE_KEY` of the array_filter and works fine.

Greetings

**Comment by soltmar** [comment]
Done :)

I will make another release this evening.

Thanks

**Comment by milorojas** [comment]
I really appreciate that :smile:
